CREATE TABLE public.users(
id INT GENERATED BY DEFAULT AS IDENTITY(INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 1000000 CACHE 1),
	email CHARACTER VARYING(320) NOT NULL,
	password CHARACTER VARYING(25) NOT NULL,
	CONSTRAINT pk_users PRIMARY KEY(id),
	CONSTRAINT uc_users_email UNIQUE(email)
);

CREATE TABLE public.employees(
id INT NOT NULL,	
	first_name CHARACTER VARYING(35) NOT NULL,
	last_name CHARACTER VARYING(35) NOT NULL,
	CONSTRAINT pk_employees PRIMARY KEY(id),
	CONSTRAINT fk_employee_users FOREIGN KEY(id) REFERENCES public.users(id)
)
CREATE TABLE public.candidates(
id INT NOT NULL,
	first_name CHARACTER VARYING(35) NOT NULL,
	last_name CHARACTER VARYING(35) NOT NULL,
	identity_number CHARACTER VARYING (11) NOT NULL,
	birth_year CHARACTER VARYING (4) NOT NULL,
	CONSTRAINT pk_candidates PRIMARY KEY(id),
	CONSTRAINT fk_candidates_users FOREIGN KEY(id) REFERENCES public.users(id),
	CONSTRAINT uc_candidates_identity_number UNIQUE (identity_number)
)

CREATE TABLE public.employers(
id INT NOT NULL,
	company_name CHARACTER VARYING(255) NOT NULL,
	web_site CHARACTER VARYING(50) NOT NULL,
	phone_number CHARACTER VARYING(12) NOT NULL,
	CONSTRAINT pk_employers PRIMARY KEY(id),
	CONSTRAINT fk_employers_users FOREIGN KEY(id) REFERENCES public.users(id)
)
CREATE TABLE public.verification_email(
id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY(INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 1000000 CACHE 1),
	is_verified BOOLEAN NOT NULL,
	CONSTRAINT pk_verification_email PRIMARY KEY(id)
)

CREATE TABLE public.verification_email_candidates(
id INT NOT NULL,
	candidates_id INT NOT NULL,
	CONSTRAINT pk_verification_email_candidates PRIMARY KEY(id),
	CONSTRAINT fk_verification_email_candidates_verification_email
	FOREIGN KEY(id) REFERENCES public.verification_email(id),
	
	CONSTRAINT fk_verification_email_candidates_candidates 
	FOREIGN KEY(candidates_id) REFERENCES public.candidates(id)
)
CREATE TABLE public.verification_email_employers(
id INT NOT NULL,
	employer_id INT NOT NULL,
	CONSTRAINT pk_verification_email_employers PRIMARY KEY(id),
	CONSTRAINT fk_verification_email_employers_verification_email 
	FOREIGN KEY(id) REFERENCES public.verification_email(id),
	CONSTRAINT fk_verification_email_employers_employers
	FOREIGN KEY(employer_id) REFERENCES public.employers(id)
)
CREATE TABLE public.employees_confirm(
id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY(INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 1000000 CACHE 1),
	employee_id INT NOT NULL,
	is_confirmed BOOLEAN NOT NULL,
	CONSTRAINT pk_employees_confirm PRIMARY KEY(id),
	CONSTRAINT fk_employees_confirm_employees
	FOREIGN KEY(employee_id) REFERENCES public.employees(id)
)
CREATE TABLE public.employees_confirm_employers(
id INT NOT NULL,
	employer_id INT NOT NULL,
	CONSTRAINT pk_employees_confirm_employers PRIMARY KEY(id),
	CONSTRAINT fk_employees_confirm_employers_employees_confirm 
	FOREIGN KEY (id) REFERENCES public.employees_confirm(id),
	
	CONSTRAINT fk_employees_confirm_employers_employers
	FOREIGN KEY(employer_id) REFERENCES public.employers(id)
)


















